#!/usr/bin/env python3
# MANAGED FILE — generated by opencode-host/generate.py.
"""Validation for the OpenCode port.

  static     adapter unit tests + structure + hash pin + managed-path hygiene
  --runtime  ALSO probe the live host registries (plugin/agent/command/skill)

Usage: python3 scripts/opencode-validate.py [--runtime] [--model provider/model]
"""
import argparse, hashlib, json, os, re, shutil, subprocess, sys, time
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PLUGIN = REPO / "opencode" / "plugin"
MANIFEST = PLUGIN / "manifest.json"
RUNTIME = PLUGIN / "runtime.ts"
INDEX = PLUGIN / "index.ts"
SHAFILE = PLUGIN / "RUNTIME.sha256"

failures, notes = [], []

def check(cond, msg):
    if not cond: failures.append(msg)

def sh(cmd, **kw):
    return subprocess.run(cmd, capture_output=True, text=True, **kw)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--runtime", action="store_true")
    ap.add_argument("--live", action="store_true")
    ap.add_argument("--model", default=os.environ.get("OPENCODE_MODEL", "ollama/deepseek-v4.1-flash:cloud"))
    a = ap.parse_args()
    m = json.loads(MANIFEST.read_text())
    check(m.get("id") and m.get("agentNamespace"), "manifest parses with id + namespace")
    check(m.get("runtimeApi"), "manifest records the probed runtime API version")

    sha = hashlib.sha256(RUNTIME.read_bytes()).hexdigest()
    check(SHAFILE.exists() and SHAFILE.read_text().strip() == sha, f"runtime.ts matches pinned sha ({sha[:12]})")
    check(m.get("canonicalRuntimeSha") == sha, "pinned sha equals the manifest's canonical sha")

    idx = INDEX.read_text()
    check('from "./runtime.ts"' in idx, "index.ts imports the pinned runtime (no inlined duplicate)")
    check("function defineHostPlugin" not in idx, "index.ts does not duplicate the runtime")
    check("defineHostPlugin(" in idx, "index.ts wires the manifest")

    check("new Function" not in RUNTIME.read_text(), "runtime performs no arbitrary JS evaluation")

    # managed artifacts must not contain developer absolute paths
    hits = []
    roots = [PLUGIN, REPO / "opencode" / "agents"]
    roots += sorted((REPO / "scripts").glob("opencode-*"))
    for root in roots:
        if not root.exists(): continue
        files = [root] if root.is_file() else [p for p in root.rglob("*") if p.is_file()]
        for p in files:
            if "node_modules" in p.parts or p.suffix not in {".md", ".json", ".ts", ".mjs", ".sh", ".py"}: continue
            if re.search(r"/home/[a-z]+/", p.read_text(errors="ignore")): hits.append(str(p.relative_to(REPO)))
    check(not hits, f"managed artifacts contain no developer absolute paths ({hits[:3]})")

    # adapter unit tests
    selftest = PLUGIN / "selftest.mjs"
    if selftest.exists() and shutil.which("node"):
        r = sh(["node", "--experimental-strip-types", str(selftest)], timeout=120)
        check(r.returncode == 0, "adapter unit tests: " + (r.stdout.strip() or r.stderr.strip()[:300]))

    # generated agents
    agents = sorted((REPO / "opencode" / "agents").glob("*.md")) if (REPO / "opencode" / "agents").is_dir() else []
    for f in agents:
        t = f.read_text(errors="ignore")
        check(t.startswith("---") and re.search(r"^mode:", t, re.M), f"generated agent ok: {f.name}")
        check(not re.search(r"^model:", t, re.M), f"generated agent is portable: {f.name}")
    n_cmds = sum(len(list((REPO / d).glob("*.md"))) for d in m.get("commandsDirs", []) if (REPO / d).is_dir())
    n_sk = sum(len([x for x in (REPO / d).iterdir() if (x / "SKILL.md").exists()]) for d in m.get("skillsDirs", []) if (REPO / d).is_dir())
    notes.append(f"canonical: {len(agents)} generated agents, {n_cmds} commands, {n_sk} skills")

    for h in m.get("hooks", []):
        check(h["claudeEvent"] == "SubagentStop", "hook event is SubagentStop")
        py = re.search(r"(\S+\.py)", h["command"])
        if py:
            rel = py.group(1).replace("{root}/", "").lstrip("/")
            check((REPO / rel).exists(), f"hook script exists: {rel}")

    # tier collapse warning
    tiers = {k: v for k, v in (m.get("tiers") or {}).items() if not k.startswith("_")}
    if tiers:
        vals = {v for v in tiers.values()}
        if len(vals) == 1 and len([k for k in tiers if k in ("opus", "sonnet", "haiku")]) > 1:
            notes.append("WARN: distinct canonical tiers collapse to one model")

    if a.runtime:
        def api(path):
            return sh(["opencode", "api", "get", path], timeout=180)
        def contains(path, needle, attempts=8):
            last = None
            for _ in range(attempts):
                r = api(path)
                last = r
                if r.returncode == 0 and needle in r.stdout:
                    return True
                time.sleep(2)
            return False
        if agents:
            names = [f.stem for f in agents]
            def missing_agents():
                miss = []
                for n in names:
                    r = api(f"/api/agent/{m['agentNamespace']}%2F{n}")
                    if not (r.returncode == 0 and f'"id":"{m["agentNamespace"]}/{n}"' in r.stdout):
                        miss.append(n)
                return miss
            miss = missing_agents()
            if miss:
                time.sleep(3)
                miss = missing_agents()
            check(not miss, f"all {len(names)} namespaced agents registered ({m['agentNamespace']}/) missing={miss[:4]}")
        if m.get("commandsDirs"):
            check(contains("/api/command", m["id"] + "/"), "namespaced commands appear in the command registry")
        if m.get("skillsDirs"):
            check(contains("/api/skill", '"path"'), "skills expose the `path` field in the skill registry")

    if a.live:
        if m.get("workflow"):
            r = sh(["opencode", "run", "--model", a.model,
                    f'Call tools["{m["id"]}"].workflow_status with runId "probe-missing" and report the raw returned text.'],
                   timeout=240, cwd=str(REPO))
            check(r.returncode == 0 and "unknown runId" in r.stdout, "workflow primitives reachable in Code Mode")
        else:
            notes.append("live probe skipped (no workflow runtime for this plugin)")

    print(f"validate {m['id']}: {'PASS' if not failures else 'FAIL'}")
    for n in notes: print("  note:", n)
    for f in failures: print("  FAIL:", f)
    return 1 if failures else 0

if __name__ == "__main__":
    sys.exit(main())
