#!/usr/bin/env bash
# MANAGED FILE — generated by opencode-host/generate.py; do not edit by hand (re-vendor instead).
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PLUGIN_DIR="$REPO_ROOT/opencode/plugin"
TARGET_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/opencode/plugins"
TARGET="$TARGET_DIR/project-euler"

[ -f "$PLUGIN_DIR/index.ts" ] || { echo "missing $PLUGIN_DIR/index.ts" >&2; exit 1; }
mkdir -p "$TARGET_DIR"
if [ -L "$TARGET" ]; then
  current="$(readlink "$TARGET")"
  [ "$current" = "$PLUGIN_DIR" ] || { echo "refusing to overwrite symlink $TARGET -> $current" >&2; exit 1; }
else
  [ -e "$TARGET" ] && { echo "refusing to overwrite existing path $TARGET" >&2; exit 1; }
  ln -s "$PLUGIN_DIR" "$TARGET"
fi
echo "plugin: $TARGET -> $PLUGIN_DIR"

AGENTS_TARGET_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/opencode/agents"
AGENTS_TARGET="$AGENTS_TARGET_DIR/project-euler"
mkdir -p "$AGENTS_TARGET_DIR"
if [ -L "$AGENTS_TARGET" ]; then
  [ "$(readlink "$AGENTS_TARGET")" = "$REPO_ROOT/opencode/agents" ] || { echo "refusing to overwrite $AGENTS_TARGET" >&2; exit 1; }
else
  [ -e "$AGENTS_TARGET" ] && { echo "refusing to overwrite $AGENTS_TARGET" >&2; exit 1; }
  ln -s "$REPO_ROOT/opencode/agents" "$AGENTS_TARGET"
fi
echo "agents: $AGENTS_TARGET -> $REPO_ROOT/opencode/agents"

echo "done. reload opencode if needed, then run scripts/opencode-validate.py"
