#!/usr/bin/env bash
# MANAGED FILE — generated by opencode-host/generate.py; do not edit by hand (re-vendor instead).
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENTRY="$REPO_ROOT/opencode/plugin/index.ts"
TARGET_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/opencode/plugins"
LOADER="$TARGET_DIR/project-euler.ts"
[ -f "$ENTRY" ] || { echo "missing $ENTRY" >&2; exit 1; }
mkdir -p "$TARGET_DIR"
# migrate a v1 directory-symlink install if present and owned
if [ -L "$TARGET_DIR/project-euler" ] && [ "$(readlink "$TARGET_DIR/project-euler")" = "$REPO_ROOT/opencode/plugin" ]; then
  rm -f "$TARGET_DIR/project-euler"; echo "migrated old symlink install"
fi
if [ -f "$LOADER" ] && ! grep -q "opencode/plugin/index.ts" "$LOADER"; then
  echo "refusing to overwrite unowned $LOADER" >&2; exit 1
fi
printf '%s\n' "// MANAGED by $REPO_ROOT/scripts/opencode-install.sh" "export { default } from \"$ENTRY\"" > "$LOADER"
echo "plugin: $LOADER -> $ENTRY"

AGENTS_SRC="$REPO_ROOT/opencode/agents"
AGENTS_TARGET_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/opencode/agents"
AGENTS_TARGET="$AGENTS_TARGET_DIR/project-euler"
mkdir -p "$AGENTS_TARGET_DIR"
if [ -e "$AGENTS_TARGET" ] && [ ! -f "$AGENTS_TARGET/.managed-by" ]; then
  echo "refusing to overwrite unowned $AGENTS_TARGET" >&2; exit 1
fi
rm -rf "$AGENTS_TARGET"
python3 "$REPO_ROOT/scripts/opencode-apply-tiers.py" "$AGENTS_SRC" "$AGENTS_TARGET" "$REPO_ROOT" || { echo "apply-tiers failed" >&2; exit 1; }
echo "agents: $AGENTS_TARGET (copied; tier models applied from tiers.local.json/env)"
echo "done. reload opencode if needed, then run scripts/opencode-validate.py --runtime"
