#!/usr/bin/env python3
# MANAGED FILE — generated by opencode-host/generate.py.
"""Copy generated agents into the installed agents dir, injecting model tiers.

The committed agent files stay portable (no machine model). This writes COPIES into
the installed location with `model:` resolved from tiers.local.json / OPENCODE_MODEL_*,
so nothing machine-specific is ever committed and re-running install refreshes tiers.
"""
import json, os, re, sys
from pathlib import Path

src, dest, repo = Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3])
dest.mkdir(parents=True, exist_ok=True)
roles = {"opus": "reasoning-heavy", "sonnet": "directed", "haiku": "cheap"}
tiers = {}
tf = repo / "opencode" / "host" / "tiers.local.json"
if tf.exists():
    try:
        tiers = {k: v for k, v in json.loads(tf.read_text()).items() if not k.startswith("_")}
    except Exception:
        tiers = {}
for alias, role in roles.items():
    v = os.environ.get("OPENCODE_MODEL_" + alias.upper()) or os.environ.get("OPENCODE_MODEL_" + role.upper().replace("-", "_"))
    if v:
        tiers[alias] = v
        tiers[role] = v

sidecar = {}
sf = src / ".tiers.json"
if sf.exists():
    try:
        sidecar = json.loads(sf.read_text())
    except Exception:
        sidecar = {}

applied = inherit = 0
for f in sorted(src.glob("*.md")):
    text = f.read_text()
    m = re.match(r"^---\n(.*?)\n---\n?(.*)$", text, re.S)
    if not m:
        (dest / f.name).write_text(text)
        continue
    fm, body = m.group(1), m.group(2)
    meta = sidecar.get(f.stem, {})
    alias = (meta.get("model") or "").lower() or None
    effort = meta.get("effort") or None
    model = None
    if alias:
        model = tiers.get(alias) or tiers.get(roles.get(alias, ""))
    if model and effort and "#" not in model:
        model = f"{model}#{effort}"
    if model:
        fm = re.sub(r"^model:.*$", "", fm, flags=re.M).rstrip()
        fm = fm + f"\nmodel: {model}"
        applied += 1
    else:
        inherit += 1
    (dest / f.name).write_text(f"---\n{fm.lstrip(chr(10))}\n---\n{body}")
(dest / ".managed-by").write_text(str(repo) + "\n")
print(f"agents installed: {applied} tier-mapped, {inherit} inherit")
