#!/usr/bin/env bash
# MANAGED FILE — generated by opencode-host/generate.py; do not edit by hand (re-vendor instead).
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PLUGIN_DIR="$REPO_ROOT/opencode/plugin"
TARGET="${XDG_CONFIG_HOME:-$HOME/.config}/opencode/plugins/project-euler"
if [ -L "$TARGET" ] && [ "$(readlink "$TARGET")" = "$PLUGIN_DIR" ]; then
  rm -f "$TARGET"; echo "uninstalled plugin: $TARGET"
else
  echo "nothing to do: $TARGET not owned by this repo"
fi

AGENTS_TARGET="${XDG_CONFIG_HOME:-$HOME/.config}/opencode/agents/project-euler"
if [ -L "$AGENTS_TARGET" ] && [ "$(readlink "$AGENTS_TARGET")" = "$REPO_ROOT/opencode/agents" ]; then
  rm -f "$AGENTS_TARGET"; echo "uninstalled agents: $AGENTS_TARGET"
fi
