#!/usr/bin/env python3
# MANAGED FILE — generated by opencode-host/generate.py.
"""Static + optional runtime validation for the OpenCode port."""
import argparse, hashlib, json, os, re, subprocess, sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MANIFEST = REPO / "opencode" / "host" / "manifest.json"
RUNTIME = REPO / "opencode" / "host" / "runtime.ts"
SHAFILE = REPO / "opencode" / "host" / "RUNTIME.sha256"

failures, notes = [], []

def check(cond, msg):
    if not cond: failures.append(msg)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--runtime", action="store_true")
    ap.add_argument("--model", default=os.environ.get("OPENCODE_MODEL", "ollama/deepseek-v4.1-flash:cloud"))
    a = ap.parse_args()
    m = json.loads(MANIFEST.read_text())
    check(m.get("id") and m.get("agentNamespace"), "manifest parses with id + namespace")
    sha = hashlib.sha256(RUNTIME.read_bytes()).hexdigest()
    check(SHAFILE.exists() and SHAFILE.read_text().strip() == sha, f"vendored runtime matches pinned sha ({sha[:12]})")
    check("from \"@opencode/plugin\"" not in RUNTIME.read_text(), "adapter needs no npm package at runtime")
    check("[\\\"path\\\"]" in RUNTIME.read_text() or "path: skillFile" in RUNTIME.read_text() or "path:" in RUNTIME.read_text(),
          "adapter uses the observed skill `path` field")

    hits = []
    scan_roots = [REPO / "opencode"]
    if (REPO / "scripts").is_dir():
        scan_roots.extend(sorted((REPO / "scripts").glob("opencode-*")))
    for root in scan_roots:
        if not root.exists():
            continue
        files = [root] if root.is_file() else [p for p in root.rglob("*") if p.is_file()]
        for p in files:
            if "node_modules" in p.parts or p.suffix not in {".md", ".json", ".ts", ".sh", ".py"}:
                continue
            try: t = p.read_text(errors="ignore")
            except Exception: continue
            if re.search(r"/home/[a-z]+/", t): hits.append(str(p.relative_to(REPO)))
    check(not hits, f"managed artifacts contain no developer absolute paths ({hits[:3]})")

    n_agents = n_cmds = n_skills = 0
    for f in sorted((REPO / "opencode" / "agents").glob("*.md")) if (REPO / "opencode" / "agents").is_dir() else []:
        n_agents += 1
        t = f.read_text(errors="ignore")
        check(t.startswith("---") and re.search(r"^mode:", t, re.M), f"generated agent frontmatter ok: {f.name}")
        check("\nmodel:" not in t, f"generated agent is portable (no machine model): {f.name}")
    for d in m.get("commandsDirs", ["commands"]):
        if (REPO / d).is_dir(): n_cmds += len(list((REPO / d).glob("*.md")))
    for d in m.get("skillsDirs", ["skills"]):
        if (REPO / d).is_dir(): n_skills += len([x for x in (REPO / d).iterdir() if (x / "SKILL.md").exists()])
    notes.append(f"canonical: {n_agents} generated agents, {n_cmds} commands, {n_skills} skills")
    for h in m.get("hooks", []):
        check(h["claudeEvent"] == "SubagentStop", "hook event is SubagentStop")
        notes.append("hook: " + h["command"])
        py = re.search(r"(\S+\.py)", h["command"])
        if py:
            rel = py.group(1).replace("{root}/", "").lstrip("/")
            check((REPO / rel).exists(), f"hook script exists: {rel}")

    if a.runtime:
        r = subprocess.run(["opencode", "run", "--model", a.model, "Reply with exactly OK"],
                           capture_output=True, text=True, timeout=240)
        check(r.returncode == 0 and "OK" in r.stdout, "opencode runtime session runs")

    print(f"validate {m['id']}: {'PASS' if not failures else 'FAIL'}")
    for n in notes: print("  note:", n)
    for f in failures: print("  FAIL:", f)
    return 1 if failures else 0

if __name__ == "__main__":
    sys.exit(main())
