// MANAGED FILE — generated by opencode-host/generate.py; do not edit by hand (re-vendor instead).
// The runtime below is pinned by RUNTIME.sha256; this file only wires it up.
import { defineHostPlugin } from "./runtime.ts"

export default defineHostPlugin({
  "agentNamespace": "project-euler",
  "agentsDirs": [
    "agents"
  ],
  "applyAgentTiers": true,
  "cage": {},
  "canonicalRuntimeSha": "4001aa56ff09f74a645abf824d0ccaa2076d922d463d9fb90abda9665eabad15",
  "commandAliases": [
    "academy",
    "basel",
    "bridges",
    "divergent",
    "eloge",
    "euler-mode",
    "jugement",
    "ledger",
    "masters",
    "opera",
    "refute",
    "scriptorium",
    "second-proof",
    "specimen"
  ],
  "commandHostNote": "---\n**OpenCode host note (managed).** In this host you orchestrate by composing the plugin's\n**safe workflow primitives** from OpenCode Code Mode \u2014 ordinary JavaScript calling\npermission-checked tools. No workflow script is ever evaluated by the plugin process.\n\n1. `const {runId} = await tools[\"project-euler\"].workflow_start({name})`\n2. Each step: `await tools[\"project-euler\"].workflow_agent({runId, prompt, agentType:\"project-euler:<cast>\",\n   label, phase, schema, timeoutMs, worktree})` \u2192 returns\n   `{ok, status, report, claim, guard, verify, output, childSessionID, sessionOutcome}`.\n3. Compose with ordinary JS: `Promise.all([...])` for parallel bearings, loops for\n   pipelines, conditionals for branching \u2014 all inside Code Mode's sandbox.\n4. Record/inspect: `workflow_phase`, `workflow_log`, `workflow_status({runId})`,\n   `workflow_cancel({runId})`, `workflow_finish`.\n\nA child's `report`/`claim` is **testimony**. `status`, `guard`, and `verify` are\nmechanical and are what the caller may rely on; the caller (Rick) independently\nre-checks. There is no hosted `/workflows` pane.",
  "commandsDirs": [
    "commands"
  ],
  "hooks": [],
  "hostTested": "2.0.14",
  "id": "project-euler",
  "name": "project-euler",
  "registerCommands": true,
  "registerMcp": true,
  "registerSkills": true,
  "runtimeApi": "opencode-2.0.14",
  "runtimeVersion": "2.0.0",
  "skillsDirs": [
    "skills"
  ],
  "tierRoles": {
    "haiku": "cheap",
    "opus": "reasoning-heavy",
    "sonnet": "directed"
  },
  "tiers": {},
  "version": "1.4.0",
  "workflow": true
})
